gplot: major clean up - removed rarely used options

diff --git a/gplot b/gplot
--- a/gplot
+++ b/gplot
@@ -42,23 +42,22 @@
 #version 1.3.9  22.01.10 -- clean up
 #version 1.3.10 09.10.10 -- added --[xyz]range option (thx to cahit)
 #version 1.4.0  23.12.11 -- removed --replot/--pid
+#version 1.4.1  24.12.11 -- major clean up - removed rarely used options
 
 usage="Usage: ${0##*/} OPTIONS <[?:?]> filename <gpoptions>"
 set=""
 range=""
 plot="plot"
-fct=""
 term=""
 defaultterm="postscript enhanced eps color"
 out=""
 gnuplot="gnuplot"
 print=""
-gp2eps=""
 multi=""
 pipe="no"
 data=""
-tee=""
 md5sum="md5sum"
+dregex="[-+]?[0-9]*\.?[0-9]+([eE][-+]?[0-9]+)?"
 
 die() {
   echo -e "$*" >&2
@@ -72,8 +71,6 @@ $usage
 
 OPTIONS:
 -3, --splot         Use splot instead of plot
--f, --fct           Use functions instead of file
-                    (disables build-in file check)
 -s, --set 'SET'     Setting some gnuplot option (may multiple)
     --[xyz]range RA Set [xyz]range, can be overwritten by --range
 -u, --unset 'SET'   Unsetting some gnuplot option (may multiple)
@@ -83,8 +80,8 @@ OPTIONS:
 -z, --zlabel LABEL  Set z label
 -t, --title  NAME   Set title
 -k, --nokey         Unset key
--r, --range TEXT    Set obscure range (may multiple x,y,z)
-                    (disable build-in range grepping)
+-r, --range TEXT    Set obscure range (may multiple x->y->z)
+                    (disable build-in range detection)
 -c, --command TEXT  Extra gnuplot command (unset etc.)
 -o, --output FILE   Plot to file (ignores -d)
                     on term "$defaultterm"
@@ -92,9 +89,7 @@ OPTIONS:
     --term TERM     Change term to TERM (only used at given -o)
                     Default: Nothing (whatever gnuplot is using)
     --tex           Same as --term "epslatex color"
-    --gp2eps        Same as --tex and -p with automatic -o and --to filename
-                    to be used with gp2eps
-    --to FILE       Same as --print but to FILE (implies -p)
+    --tex2          Same as --term "epslatex color standalone"
 -d, --dumb          Same as --term dump (useful for console)
 -w, --wxt           Same as --term wxt (allow to rescale)
 -p, --print         Print command instead of running gnuplot
@@ -102,11 +97,8 @@ OPTIONS:
     --gnuplot NAME  Change the gnuplot command
                     Default: "$gnuplot"
 -i, --pipe          Switch on reading data from STDIN by hand (useful, with --)
-    --tee           like --pipe but print also data to STDOUT
-                    (ignores --print, --to)
---                  All following arguments are files and plot options
-                    (Ranges option will still be checked by grep, unless -r given)
-                    useful for plotting multiple files (BUT quote yourself!)
+    --              All following arguments are files and plot options (Mind quotes)
+                    (Ranges option will still be checked, but not files)
 -h, --help          Show this help
 -v, --version       Show version
     --gversion      Show gnuplot version (may use --gnuplot before)
@@ -119,71 +111,57 @@ Examples: ${0##*/} [1:2][2:3] file.d u 1:2
           ${0##*/} -3fs pm3d x*y w pm3d
           ${0##*/} -- '"data" u 1:2, "data" u 1:3 w l'
           ${0##*/} -c "unset key" data u 1:2
-          seq 1 10 | ${0##*/} -r "[:][0:12]" --tee - 't "data"'
-          seq 1 2 | gplot
+          seq 1 10 | ${0##*/} -r "[:][0:12]" - 't "data"'
+          seq 1 2 | ${0##*/}
 
 Send comments and bugs to: junghans@mpip-mainz.mpg.de
 eof
 }
 
-while [ "${1#-}" != "$1" ] && [ -n "${1#-}" ]; do
-
- #hack to split short opts
- #no long opt and combined short opt
- if [ "${1#--}" = "$1" ] && [ -n "${1:2}" ]; then
-    #if first short opt need argument
-    if [ "${1#-[cmorstuxyz]}" != "${1}" ]; then
-       set -- "${1:0:2}" "${1:2}" "${@:2}"
-    else
-       #mind the - here !
-       set -- "${1:0:2}" "-${1:2}" "${@:2}"
+shopt -s extglob
+while [[ ${1} = -?* ]]; do
+  if [[ ${1} = --*=* || ${1} = -?=* ]]; then # case --xx=yy
+    set -- "${1%%=*}" "${1#*=}" "${@:2}" # --xx=yy to --xx yy
+  elif [[ ${1} = -[^-]?* ]]; then # case -xy split
+    if [[ ${1} = -[sumxytrco]* ]]; then #short opts with arguments
+       set -- "${1:0:2}" "${1:2}" "${@:2}" # -xy to -x y
+    else #short opts without arguments
+       set -- "${1:0:2}" "-${1:2}" "${@:2}" # -xy to -x -y
     fi
  fi
-
  case $1 in 
    -s | --set)
-     set="${set}set $2\n"
+     set+="set $2\n"
      shift 2 ;;
    -u | --unset)
-     set="${set}unset $2\n"
+     set+="unset $2\n"
      shift 2 ;;
    -m | --ymarker)
-     if [ -n "$(echo "$2" | grep -e "^[-.eE[:digit:]]*$")" ]; then
-       set="${set}set arrow from $2, graph 0 to $2, graph 1 nohead lt -1 \n"
-     else
-       die "Marker argument '$2' has to be a number"
-     fi
+     [[ $2 =~ ^$dregex$ ]] || die "Marker argument '$2' has to be a number"
+     set+="set arrow from $2, graph 0 to $2, graph 1 nohead lt -1 \n"
      shift 2 ;;
-   -x | --xlabel)
-     set="${set}set xlabel \"${2}\"\n"
-     shift 2 ;;
-   -y | --ylabel)
-     set="${set}set ylabel \"${2}\"\n"
-     shift 2 ;;
-   -z | --zlabel)
-     set="${set}set ylabel \"$2\"\n"
+   -[xyz] | --[xyz]label)
+     set+="set ${1//[^xyz]}label '${2}'\n"
      shift 2 ;;
    -t | --title)
-     set="${set}set title \"$2\"\n"
+     set+="set title '$2'\n"
      shift 2 ;;
    -k | --nokey)
-     set="${set}unset key\n"
+     set+="unset key\n"
      shift ;;
    -r | --range)
-     range="${range}$2"
+     range+="$2"
      shift 2 ;;
    --[xyz]range)
-     set="${set}set ${1##--} $2\n"
+     set+="set ${1##--} $2\n"
      shift 2 ;;
    -c | --command)
-     set="${set}$2\n"
+     set+="$2\n"
      shift 2 ;;
    -o | --output)
      out="$2"
      #if term was not set before
-     if [ -z "$term" ]; then
-       term="$defaultterm"
-     fi
+     [[ -z $term ]] && term="$defaultterm"
      shift 2 ;;
    -- )
      multi="yes"
@@ -192,21 +170,11 @@ while [ "${1#-}" != "$1" ] && [ -n "${1#-}" ]; do
    --term)
      term="$2"
      shift 2 ;;
-   --tee)
-     tee="yes"
-     pipe="yes"
-     shift ;;
    --tex)
      term="epslatex color"
      shift ;;
-   --to)
-     print="yes"
-     to="$2"
-     shift 2 ;;
-   --gp2eps)
-     term="epslatex color"
-     print="yes"
-     gp2eps="yes"
+   --tex2)
+     term="epslatex color standalone"
      shift ;;
    -d | --dumb)
      term="dumb"
@@ -216,9 +184,6 @@ while [ "${1#-}" != "$1" ] && [ -n "${1#-}" ]; do
      shift ;;
    -3 | --splot)
      plot="splot"
-     shift ;;
-   -f | --fct)
-     fct="yes"
      shift ;;
    -p | --print)
      print="yes"
@@ -248,89 +213,33 @@ done
 
 # if frange is not already defined check for first char, [ which implies a range
 if [[ -z $range && ${1} = "["* ]]; then
- if [[ "$plot" = "plot" ]]; then
-   #check for [??:??] or [??:??]{??:??}
-   [ -n "$(echo "$1" | grep -e '^\(\[[-.eE[:digit:]]*:[-.eE[:digit:]]*\]\)\{1,2\}$')" ] || 
-     die "Range ('$1') has to be in form [??:??]\<[??:??]\>"
-   range=$1
-   shift
- fi
- if [ "$plot" = "splot" ]; then
-   #check for [??:??] or [??:??]{??:??} or [??:??]{??:??}[??:??]
-   [ -n "$(echo "$1" | grep -e '^\(\[[-.eE[:digit:]]*:[-.eE[:digit:]]*\]\)\{1,3\}$')" ] ||
-     die "Range ('$1') has to be in form [??:??]\<[??:??]\>\<[??:??]\>"
-   range=$1
-   shift
- fi
+  [[ $plot = splot ]] && n=3 || n=2
+  [[ $1 =~ ^(\[$dregex:$dregex\]){1,$n}$  ]] || die "Range has strange form use --range option"
+  range="$1"
+  shift
 fi
 
 #no agrument left -> read from pipe (add argument -)
-[[ -z "$1" ]] && set -- "-"
+[[ -z $1 ]] && set -- "-"
 
 #multiple files - take the rest as gpcommand
-if [ "$multi" = "yes" ]; then
-  gpcommand="$*"
+if [[ $multi = yes ]]; then
+  gpcommand="$@"
 else
-  file=$1
-  shift
-  [[ "$file" = "-" ]] && pipe="yes"
-  if [ "$fct" = "yes" ]; then
-    gpcommand="$file $*"
-  else
-    #if function are disabled, check for file
-    if [ "$pipe" != "yes" ]; then
-      [ -r "$file" ] || die "file '$file' not found !\nRemaining argument MUST be a file or use --fct"
-      #create name of output name out of data filename, if no -o given
-      [[ -n "$gp2eps" ]] && [[ -z "$out" ]] && out="${file%.*}_pre.eps"
-      #create name of to name out of data filename, if no --to given
-      [[ -n "$gp2eps" ]] && [[ -z "$to" ]] && to="${file%.*}.gp"
-    fi
-    #add " to filename
-    gpcommand="\"$file\" $*"
-  fi
+  [[ $1 = "-" ]] && pipe="yes"
+  [[ $1 != '-' && ! -r $1 ]] && die "file '$1' not found !\n1st argument MUST be a file or use -- option"
+  #add " to filename
+  gpcommand="'$1' ${@:2}"
 fi
 
-#for gp2eps: if no -o and --to was given, when using -- or pipe
-[ -n "$gp2eps" ] && ( [ -z "$to" ] || [ -z "$out" ] ) && \
-  die "Missing --to or -o option for --gp2eps\nOptions like --fct, --, --pipe disable automatic names!"
-
-#set output
-[[ -n "$out" ]] && set="${set}set output \"$out\"\n"
-
-#set term
-[[ -n "$term" ]] && set="set terminal $term\n${set}"
-
-#if term is X11, aqua or defautlt gnuplot has to persist
-if [ "$term" = "x11" ] || [ "$term" = "wxt" ] || [ "$term" = "aqua" ] || [ -z "$term" ]; then
-   gnuplot="$gnuplot -persist"
-fi
-
-#add - as file to gpcommand and readin data
-if [ "$pipe" = "yes" ]; then
-  #multi disable all build-in features
-  data="#BEGIN DATA"
-  while read -r; do
-    data="${data}\n${REPLY}"
-  done
-  data="${data}\n#END DATA"
-fi
-#build shell command
-command="${set}$plot $range $gpcommand"
-
-#Run gnuplot if no -p given
-if [ "$tee" = "yes" ] || [ -z "$print" ]; then
-  echo -e "${command}\n${data}" | $gnuplot || \
-    die "gnuplot finished with error !"
-  if [ "$tee" = "yes" ]; then
-    #print and delete first line ("\n")
-    echo -e "$data" | sed '1d;$d'
-  fi
-#print
-else
-  # to file or to stdout ?
-  if [ -z "$to" ]; then
-    echo -e "$command\n$data"
-  else
-    echo -e "$command\n$data" > $to
-  fi
-fi
+#if term is X11, aqua or default gnuplot has to persist
+[[ $term = @(x11|wxt|aqua) || -z $term ]] && gnuplot+=" -persist"
+[[ $print = yes ]] && gnuplot="cat"
+{
+  [[ -n $term ]] && echo -e "set terminal $term"
+  [[ -n $out ]] && echo -e "set output '$out'"
+  echo -e "${set}"
+  echo -e "$plot $range $gpcommand"
+  [[ $pipe = yes ]] && cat
+} | $gnuplot || \
+  die "$gnuplot finished with error !"
